# Generated by Django 4.1.7 on 2023-03-23 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0004_menu_menu_point_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
